pugna@pugna-pc:~/Project/server_inside_docker$ python http_server.py127.0.0.1 - - [29/Sep/2015 17:09:05] "GET /sent_test HTTP/1.1" 200 -~~~~~~('x\x9c34\x02\x00\x00\x96\x00dx\x9c36\x01\x00\x00\x9c\x00hx\x9c35\x03\x00\x00\xa2\x00lx\x9c3\xb7\x00\x00\x00\xa8\x00px\x9c\xb3\xb4\x04\x00\x00\xad\x00sx\x9c\xe3\x02\x00\x00\x0b\x00\x0bx\x9c\x03\x00\x00\x00\x00\x01x\x9c\x03\x00\x00\x00\x00\x01x\x9c\x03\x00\x00\x00\x00\x01x\x9c\x03\x00\x00\x00\x00\x01', 2)----------------------------------------Exception happened during processing of request from ('127.0.0.1', 42341)Traceback (most recent call last):  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock    self.process_request(request, client_address)  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request    self.finish_request(request, client_address)  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request    self.RequestHandlerClass(request, client_address, self)  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__    self.handle()  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle    self.handle_one_request()  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request    method()  File "http_server.py", line 48, in do_GET    file_response = self.decompress_(buff, int(compress_size))  File "http_server.py", line 104, in decompress_    dezip_str = zlib.decompress(content)error: Error -5 while decompressing data: incomplete or truncated stream----------------------------------------pugna@pugna-pc:~/Project/server_inside_docker$ python http_agent.py127.0.0.1 - - [29/Sep/2015 17:09:05] "GET /sent_test HTTP/1.1" 200 -('x\x9c34\x02\x00\x00\x96\x00dx\x9c36\x01\x00\x00\x9c\x00hx\x9c35\x03\x00\x00\xa2\x00lx\x9c3\xb7\x00\x00\x00\xa8\x00px\x9c\xb3\xb4\x04\x00\x00\xad\x00sx\x9c\xe3\x02\x00\x00\x0b\x00\x0bx\x9c\x03\x00\x00\x00\x00\x01x\x9c\x03\x00\x00\x00\x00\x01x\x9c\x03\x00\x00\x00\x00\x01x\x9c\x03\x00\x00\x00\x00\x01', 2)~~~~~~